version: '2'
services:
  data-producer-service:
    image: black-hole-data-producer
    mem_limit: 700m
    ports:
      - "8001:8001"
    networks:
      - black-hole-network
    build:
      context: ./data-producer
      dockerfile: Dockerfile
    depends_on:
      - zookeeper
      - kafka
    env_file:
      - ./.env

  topic-viewer-service:
    image: topic-viewer
    mem_limit: 700m
    ports:
      - "8002:8002"
    networks:
      - black-hole-network
    build:
      context: ./topic-viewer
      dockerfile: Dockerfile
    depends_on:
      - zookeeper
      - kafka
    env_file:
      - ./.env

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - black-hole-network
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_LISTENERS: INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "${TOPIC_BH_SENSORS_EVENT_NAME}:${TOPIC_BH_SENSORS_EVENT_PARTITIONS}:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - black-hole-network

networks:
  black-hole-network: