version: '2'
services:
  data-producer-service:
    image: black-hole-data-producer
    mem_limit: 700m
    ports:
      - "8001:8001"
    networks:
      - black-hole-network
    build:
      context: ./data-producer
      dockerfile: Dockerfile
    depends_on:
      - zookeeper
      - kafka
    env_file:
      - ./.env

#  topic-viewer-service:
#    image: topic-viewer
#    mem_limit: 700m
#    ports:
#      - "8002:8002"
#    networks:
#      - black-hole-network
#    build:
#      context: ./topic-viewer
#      dockerfile: Dockerfile
#    depends_on:
#      - zookeeper
#      - kafka
#    env_file:
#      - ./.env

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - black-hole-network
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_LISTENERS: INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "${TOPIC_BH_SENSORS_EVENT_NAME}:${TOPIC_BH_SENSORS_EVENT_PARTITIONS}:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - black-hole-network

  schema-registry:
    image: confluentinc/cp-schema-registry:5.4.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_LISTENERS: ${SCHEMA_REGISTRY_URL}
    networks:
      - black-hole-network

#  control-center:
#    image: confluentinc/cp-enterprise-control-center:5.4.0
#    hostname: control-center
#    container_name: control-center
#    depends_on:
#      - zookeeper
#      - kafka
#      - schema-registry
#    ports:
#      - "9021:9021"
#    environment:
#      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
#      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
#      CONTROL_CENTER_REPLICATION_FACTOR: 1
#      PORT: 9021
#    networks:
#      - black-hole-network

networks:
  black-hole-network: