version: '2'
services:
  data-producer-service:
    image: black-hole-data-producer
    mem_limit: 700m
    ports:
      - "8001:8001"
    networks:
      - black-hole-network
    build:
      context: ./data-producer
      dockerfile: Dockerfile
    depends_on:
      - zookeeper
      - kafka
    environment:
      SPRING_KAFKA_CONSUMER_BOOTSTRAP-SERVERS: kafka:9092
      SPRING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS: kafka:9092

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - black-hole-network
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_LISTENERS: INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "bh-sensors-event:2:1"
    depends_on:
      - zookeeper
    networks:
      - black-hole-network

networks:
  black-hole-network: